"""Create games table

Revision ID: 9049262a8c96
Revises: 3cf5ba457650
Create Date: 2023-12-12 19:34:33.628966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9049262a8c96'
down_revision = '3cf5ba457650'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###